version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - sudo aws --version
      - sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 784733298322.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=784733298322.dkr.ecr.us-east-1.amazonaws.com/myrepo
      - IMAGE_TAG=buildimage
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sudo docker build docker1 -t $REPOSITORY_URI:latest .
      - sudo docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - sudo docker push $REPOSITORY_URI:latest
      - sudo docker push $REPOSITORY_URI:$IMAGE_TAG

