version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - pwd="$(aws ecr get-login  --region us-east-1 | awk '{print $6}')"
      - sudo docker login -u AWS -p "$pwd" https://784733298322.dkr.ecr.us-east-1.amazonaws.com
      #- aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 784733298322.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=784733298322.dkr.ecr.us-east-1.amazonaws.com/myrepo
      - IMAGE_TAG=buildimage
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build docker1 -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

